### ISSUE TITLE
Autodiscover arch

### ISSUE THREAD

**Issue by onedr0p** [githubixx/ansible-role-cilium-cli#14]
Hi 👋🏼 

I was looking to use your role however it would be nice if it could also auto discover the architecture of the machine it is running on.

Maybe an option of:

```yaml
cilium_cli_arch: "auto"
```

Thanks!

**Comment by githubixx** [comment]
Hello. Well that feature would be nice but there is no match between Ansible and the architecture that is part of the package name. E.g. Ansible provides only this variables that could be used:

```
    "ansible_architecture": "x86_64",
    "ansible_machine": "x86_64",
    "ansible_userspace_architecture": "x86_64",
```

But the package name contains `amd64` e.g. So a mapping would be needed and I don't have that information for all architectures.

**Comment by onedr0p** [comment]
Yeah, that can get a bit tedious to try and match up `ansible_architecture` to the release filenames. FWIW I have at least the most popular architectures (amd64 and arm64) mapped out here and it works fine.

https://github.com/onedr0p/flux-cluster-template/blob/3116a104294952336c79f609843d8883a2a5845d/ansible/playbooks/cluster-prepare.yml#L52

I'll go ahead and close this issue as the above link works fine for my usecase.
